language: python
python:
  - "3.5"
install: "pip3 install -r requirements.txt"
script:
 - "python3 test_authentication.py"
 - "python3 test_level_access.py"
 - "python3 test_views.py"
 - "python3 test_db_layer.py"
 before_deploy: "echo 'ready?'"
 deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
after_deploy:
  - ./after_deploy_1.sh
  - ./after_deploy_2.sh    